-- CreateTable
CREATE TABLE "Attendees" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "eventsId" TEXT NOT NULL,
    CONSTRAINT "Attendees_eventsId_fkey" FOREIGN KEY ("eventsId") REFERENCES "Events" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
